/**
 * compiler.c – Driver program for the mini-c compiler
 * 
 * Rohan Kartha, April 2024
 * 
*/

#include "ast/ast.h"
#include "y.tab.h"
#include <stdlib.h>
#include <stdio.h>
#include <cstddef>
#include <vector>
#include "semantic-analysis.h"
extern FILE* yyin;
extern int yylex_destroy();

/**************** global variables ****************/
ast_Node* root = NULL;


/**************** main ****************/
int main(int argc, char* argv[]) 
{
    // Open mini-c file
    if (argc == 2) {
        yyin = fopen(argv[1], "r");

        if (yyin == NULL) {
            fprintf(stderr, "File open error");
            return 1;
        }
    }

    // Conduct lexical and syntax analysis of mini-c file
    yyparse();
    if (argc == 2) {
        fclose(yyin);
    }
    yylex_destroy();

    // Print abstract syntax tree (AST) generated by syntax analysis
    printNode(root);

    // Conduct semantic analysis
    bool result = semanticAnalysis();

    if (result) {
        printf("Semantic analysis passed\n");
    }
    else {
        printf("Semantic analysis NOT passed\n");
    }

    // Free memory holding AST
    freeNode(root);

    return 0;
}